config/routes.rb
Rails.application.routes.draw do
  root 'galleryhomepage#index'

  controller :about do
    get 'about-us' => 'about#index'
  end

  get 'tags/show'

  get 'api/pieces' => 'galleryhomepage#api'

  resources :organizations do
    resources :spaces
  end

  controller :artists do
    get 'local_artists' => 'artists#local_artists'
    get 'user_location' => 'artists#user_location'
  end

  controller :spaces do
    get 'spaces' => 'spaces#all_spaces'
    
  end

  controller :pieces do
    get 'pieces' => 'pieces#all_pieces'
  end

  resources :tags, only: [:show]

  resources :artists do
    resources :pieces
  end

  resources :sessions, only: [:new, :create, :destroy]

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    post 'logout' => :destroy
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :pieces
  has_many :spaces
  has_secure_password
  validates :email, presence: true
  validates :password, length: { minimum: 6 }
  geocoded_by :address
  after_validation :geocode
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  include ArtistsHelper
  def index
    @artists = Artist.all
    @organization = Organization.find_by(id: session[:organization_id])
  end

  def user_location
  end

  def local_artists
    @lat = [params[:lat]]
    @long = [params[:lng]]
    @artists =  Artist.near([params[:lat], params[:lng]], 5)
  end

  def show
    @artist = Artist.find_by(id: params[:id])
    @pieces = @artist.pieces
    @citystate = @artist.address.scan(/(.+?),\s*(.+?)(?:,\s|\s\s)(.+?)\s(\d{5})/)
    @location= @citystate[0][1] + ", " + @citystate[0][2]

  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render 'new'
    end
  end

  def edit
    @artist = Artist.find_by(id: params[:id])
  end

  def update
    @artist = Artist.find_by(id: params[:id])
    if @artist.update(artist_params)
      redirect_to artist_path
    else
      render 'edit'
    end
  end

  def destroy
    @artist = Artist.find_by(id: params[:id])
    @artist.destroy
    redirect_to root_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :email, :password, :address, :facebook, :twitter, :website, :bio, :avatar)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def find_artist_tags(artist)
    @tags = []
    artist.pieces.each do |piece|
      piece.tag_list.each do |tag|
        @tags << tag
      end
    end
    @tags.uniq!
  end

  def current_user
    if Artist.find_by_id(session[:artist_id])
      @current_user ||= Artist.find_by_id(session[:artist_id])
    elsif Organization.find_by_id(session[:organization_id])
      @current_user ||= Organization.find_by_id(session[:organization_id])
    end
  end

end

app/views/artists/_artists.html.erb
<div class="row">
<% @artists.each do |artist| %>
		<div class="col-sm-3">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

            <div class="card hovercard">
                <div class="cardheader">

                </div>
                <% unless artist.pieces[0].nil? %>
                <script type="text/javascript">
                    $('div .cardheader').last().css('background', "url(<%= "#{artist.pieces.sample.image.url(:medium)}" %>)");
                </script>
                <% end %>
                <div class="avatar">
                    <%= link_to image_tag(artist.avatar), artist_path(artist) %>
                </div>
                <div class="info">
                    <div class="title">
                        <%= link_to artist.name, artist_path(artist) %>
                    </div>
                    <div class=""><%= link_to artist.website, "http://#{artist.website}" %></div>
                    <div class="desc"><%= "#{artist.bio}" %></div>
                    <div><%= artist.address.scan(/(.+?),\s*(.+?)(?:,\s|\s\s)(.+?)\s(\d{5})/)[0][1] + ", " + artist.address.scan(/(.+?),\s*(.+?)(?:,\s|\s\s)(.+?)\s(\d{5})/)[0][2] %></div>
                </div>
                <div class="bottom">
                    <% if artist.twitter %>
                    <a class="btn card-btn btn-primary btn-twitter btn-sm" href="<%= "http://twitter.com/#{artist.twitter}" %>">
                        <i>t</i>
                    </a>
                    <% end %>
                    <% if artist.facebook %>
                    <a class="btn card-btn btn-primary btn-sm" rel="publisher"
                       href="<%= "http://#{artist.facebook}" %>">
                        <i>f</i>
                    </a>
                    <% end %>
                </div>
            </div>
        </div>
<% end %>

app/views/artists/_form.html.erb
    <%= form_for @artist, class:"form-horizontal" do |f| %>
      <form>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.text_field :avatar, class:"form-control", placeholder:"myimagehostingsite.com/coolavatar.jpg" %>
        </div>
        <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control", placeholder:"Chris Doe" %>
        </div>
        <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class:"form-control", placeholder:"chris@example.com" %>
        </div>
        <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class:"form-control", placeholder:"MyTot3sSecurePassw0r!ds" %>
        </div>
        <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class:"form-control", placeholder:"Street, City, State, Zipcode" %>
        </div>
        <div class="form-group">
        <%= f.label :facebook %>
        <%= f.text_field :facebook, class:"form-control", placeholder:"facebook.com/myfacebookpage" %>
        </div>
        <div class="form-group">
        <%= f.label :twitter %>
        <%= f.text_field :twitter, class:"form-control", placeholder:"@handle" %>
        </div>
        <div class="form-group">
        <%= f.label :website %>
        <%= f.text_field :website, class:"form-control", placeholder:"www.example.com" %>
        </div>
        <div class="form-group">
        <%= f.label :bio %>
        <%= f.text_field :bio, class:"form-control", placeholder:"Here's a blurb about me" %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
    <% end %>
</form>
<br>
<%= link_to "Destroy Profile", @artist,class: 'btn btn-primary', method: :delete %>

app/views/artists/create.html.erb
<h1>Artists#create</h1>
<p>Find me in app/views/artists/create.html.erb</p>

app/views/artists/destroy.html.erb
<h1>Artists#destroy</h1>
<p>Find me in app/views/artists/destroy.html.erb</p>

app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %>'s Profile</h1>

<%= render 'form' %>

app/views/artists/index.html.erb
<script src="http://maps.googleapis.com/maps/api/js"></script>
<h1 class="c-t">Artists Using Scene</h1>
<script>

$(document).ready(function(){
    initializeMap();
});

function initializeMap() {
  var mapOptions = {
    zoom: 8,
    mapTypeId:google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("googleMap"),mapOptions);
    setLocation(map);
  };

  var setLocation = function(map) {
   navigator.geolocation.getCurrentPosition(function(position) {
   var userLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        map.setCenter(userLocation);
        mapSetup(userLocation, map);
   });
 }

  var mapSetup =  function (userLocation, map){

      var userIcon = {
        url: "images/user_icon.png",
        anchor: new google.maps.Point(14,28)
          };
       var userInfowindow = new google.maps.InfoWindow({
        content: '<img class="c-img73 img-circle img-center center-block fl-st" src="/images/user_anon.png"></img>'+'<div class="c ml-2"> Hi! You are here!</div>'
         });
      var userMarker = new google.maps.Marker({
        position: userLocation,
        icon: userIcon,
        infowindow: userInfowindow
      });
      userMarker.setMap(map);
      google.maps.event.addListener(userMarker, 'click', function(){
        userInfowindow.open(map, this);
      });

      var artistIcon =  '/images/artist_icon.png';
       <% @artists.each do |artist|%>
       var markerLatLong = new google.maps.LatLng(<%= artist.latitude%>, <%= artist.longitude %>);

       var myInfowindow = new google.maps.InfoWindow({
        content: '<img class="c-img73 img-circle img-center center-block fl-st" src="<%= artist.avatar%>"></img>'+'<div class="c ml-2">My name is <%= link_to artist.name,artist_path(artist) %></div>'
         });

       var marker = new google.maps.Marker({
        position: markerLatLong,
        icon: artistIcon,
        map: map,
        infowindow:myInfowindow
       });

      google.maps.event.addListener(marker, 'click', function(){
       this.infowindow.open(map, this);
      });
      <% end %>
}
</script>

<div class='m0-a' id="googleMap" style="width:100%;height:500px;"></div>

<%=link_to 'Local Artists', user_location_path, class:'btn btn-primary btn-block' %>
<%= render 'artists' %>

app/views/artists/local_artists.html.erb
<script src="http://maps.googleapis.com/maps/api/js"></script>
<h1 class="c-t">Local Artists</h1>
<script>


$(document).ready(function(){
    initializeMap();
});

function initializeMap() {
  var mapOptions = {
    zoom: 13 ,
    mapTypeId:google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("googleMap"),mapOptions);
    setLocation(map);
  };

  var setLocation = function(map) {
   navigator.geolocation.getCurrentPosition(function(position) {
   var userLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        map.setCenter(userLocation);
        mapSetup(userLocation, map);
   });
 }

  var mapSetup =  function (userLocation, map){
      //var userIcon = '/images/user_icon.png';
      var userIcon = {
        url: "images/user_icon.png",
        anchor: new google.maps.Point(14,28)
          };
      var userInfowindow = new google.maps.InfoWindow({
        content: '<img class="c-img73 img-circle img-center center-block fl-st" src="/images/user_anon.png"></img>'+'<div class="c ml-2"> Hi! You are here!</div>'
         });
      var userMarker = new google.maps.Marker({
        position: userLocation,
        icon: userIcon,
        infowindow: userInfowindow
      });
      userMarker.setMap(map);
       google.maps.event.addListener(userMarker, 'click', function(){
       userInfowindow.open(map, this);
      });
      var artistIcon =  '/images/artist_icon.png';
       <% @artists.each do |artist|%>
       var markerLatLong = new google.maps.LatLng(<%= artist.latitude%>, <%= artist.longitude %>);

       var myInfowindow = new google.maps.InfoWindow({
        content: '<img class="c-img73 img-circle img-center center-block fl-st" src="<%= artist.avatar%>"></img>'+'<div class="c ml-2">My name is <%= link_to artist.name,artist_path(artist) %></div>'
         });

       var marker = new google.maps.Marker({
        position: markerLatLong,
        icon: artistIcon,
        map: map,
        infowindow:myInfowindow
       });

      google.maps.event.addListener(marker, 'click', function(){
       this.infowindow.open(map, this);
      });
      <% end %>
}



</script>
<div class='m0-a' id="googleMap" style="width:100%;height:500px;"></div>
<%=link_to 'All Artists', artists_path, class:'btn btn-primary btn-block' %>
<%= render 'artists' %>

app/views/artists/new.html.erb
<div class="container">
    <div class="row">
        <div class="span12">
          <h1>Artist Sign-Up</h1>
          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/artists/show.html.erb
 <div class=" mt-2">
 <img class="m0-a profpic b-black-1" src="<%= @artist.avatar %>">
</div>
 <div class="bo-b-black-2 p-b-1 mb-4">
    <div class="span-3-d m0-a ta-c">
        <h1><%=@artist.name %></h1>
    </div>
    <div class="span-3-d m0-a ta-c">
        <a href="<%=@artist.website%>"><%= @artist.website %></a>
    </div>

    <div class="span-3-d m0-a ta-c p-t-2 p-b-2">
        <%=@artist.bio %>
    </div>
    <div class="span-3-d m0-a ta-c">
        <a href="<%=@artist.email%>"><%= @artist.email %></a>
    </div>
    <div class="span-3-d m0-a ta-c">
        <h4><%=@location%><h4>
        </div>
        <div class="social-media span-3-d m0-a ta-c">
            <% if @artist.twitter %>
            <a class="btn card-btn btn-primary btn-twitter btn-sm" href="<%= "http://twitter.com/#{@artist.twitter}" %>">
                <i>t</i>
            </a>
            <% end %>
            <% if @artist.facebook %>
            <a class="btn card-btn btn-primary btn-sm" rel="publisher"
            href="<%= "http://#{@artist.facebook}" %>">
            <i>f</i>
        </a>
        <% end %>
    </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
      zoomHover();
  })
</script>
<div class="debugx span-11-d mb-15 ">
  <div class="debugx ml-25">

    <div id="target"></div>
    <div class="debugx allpics">
        <% @artist.pieces.each do |piece| %>
        <div class="debugx fl-end m-1 viewport">
            <a class="pic" href="<%= piece.image.url %>" data-lightbox="ex-1" >
                <span class="dark-background"> <%= piece.title %> <em>by <%= @artist.name %></em></span>
                <img src="<%= piece.image.url(:thumb) %>" alt="Piece Pic" class="image-style" />
            </a>
        </div>
        <% end %>
        <% @artist.spaces.each do |space| %>
        <div class="debugx fl-end m-1 viewport">
            <a class="pic" href="<%= space.image.url %>" data-lightbox="ex-1" >
                <span class="dark-background"> <%= space.title %> <em>by <%= @artist.name %></em></span>
                <img src="<%= space.image.url(:thumb) %>" alt="Piece Pic" class="image-style" />
            </a>
        </div>
        <% end %>
    </div>
</div>

</div>
<% if session[:artist_id] == @artist.id %>
    <%= link_to new_artist_piece_path(@artist) do %>
    <div class="debugx fl-end m-1 viewport new"></div>
    <% end %>
<% end %>
<div class="col mb-8"></div>

app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>

app/views/artists/user_location.html.erb
<html>
<head>
  <title></title>
<img src="/images/loading.gif"  class="c-l-img">
  <script src="http://maps.googleapis.com/maps/api/js"></script>
<script>

$('document').ready(function(){

  initializeMap();

});



var data;
function initializeMap() {
  var mapOptions = {
    zoom: 14 ,
    mapTypeId:google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("googleMap"),mapOptions);
   navigator.geolocation.getCurrentPosition(function(position) {

            var geolocate = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

            var lat = position.coords.latitude;
            var lng = position.coords.longitude
            newDoc(lat, lng);
            console.log(data);


});
}


 function newDoc(lat, lng) {
    window.location = "http://localhost:3000/local_artists?lat=" + lat +"&lng=" +lng;
}
</script>
</head>
<body>
<div id="googleMap"></div>

</body>
</html>