config/routes.rb
Rails.application.routes.draw do
  root 'galleryhomepage#index'

  controller :about do
    get 'about-us' => 'about#index'
  end

  get 'tags/show'

  get 'api/pieces' => 'galleryhomepage#api'

  resources :organizations do
    resources :spaces
  end

  controller :artists do
    get 'local_artists' => 'artists#local_artists'
    get 'user_location' => 'artists#user_location'
  end

  controller :spaces do
    get 'spaces' => 'spaces#all_spaces'
    
  end

  controller :pieces do
    get 'pieces' => 'pieces#all_pieces'
  end

  resources :tags, only: [:show]

  resources :artists do
    resources :pieces
  end

  resources :sessions, only: [:new, :create, :destroy]

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    post 'logout' => :destroy
  end

end

app/models/piece.rb
class Piece < ActiveRecord::Base
  belongs_to :artist
  acts_as_taggable
  acts_as_taggable_on :skills, :interests

  has_attached_file :image, styles: { medium: "750x600>", thumb: "450x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  include TagsHelper

  def all_pieces
    @pieces = Piece.all
    @pieces.shuffle
    pull_tags(@pieces)
  end

  def index
    @artist = Artist.find(params[:artist_id])
    @pieces = @artist.pieces
  end

  def show
    @artist = Artist.find(params[:artist_id])
    # @piece = Piece.find_by(artist_id: params[:artist_id])
    @piece = Piece.find(params[:id])
    render partial: "partials/show_piece", locals: { artist: @artist, piece: @piece }
  end

  def new
    @artist = Artist.find(params[:artist_id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @piece = @artist.pieces.new(piece_params)
    if @piece.save
      @piece.tag_list.add(params[:tag_list])
      redirect_to artist_piece_path(@artist, @piece)
    else
      render 'new'
    end
  end

  def edit
    @artist = Artist.find(params[:artist_id])
    @piece = Piece.find(params[:id])
  end

  def update
    @piece = Piece.find(params[:id])
    if @piece.update(piece_params)
      redirect_to artist_piece_path(@piece.artist_id, @piece)
    else
      render 'edit'
    end
  end

  def destroy
    @piece = Piece.find(params[:id])
    @artist = Artist.find(params[:artist_id])
    @piece.destroy
    redirect_to artist_path(@artist)
  end

  private
  def piece_params
    params.require(:piece).permit(:img, :title, :description, :tag_list, :image)
  end
end

# add and remove multiple tags in an array
# @user.tag_list.add("graffiti", "awesome")
# @user.tag_list.remove("graffiti", "awesome")
# @user.tag_list to return of tag.names
# @user.tags to return tag objects

# add skills to artist
# @artist.skill_list = "spray paint, acryllic, oil"
# @artist.save
# @artist.skills => ['spray paint', acryllic, oil]

# finding tagged objects
# @piece.tagged_with(['tag_name, tag_name2']) returns objects

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/_form_piece_scene.html.erb
<%= form_for ([user, picture]) do |f| %>
  <p>Image URL</p>
  <%= f.text_field :img %>

  <p>Title</p>
  <%= f.text_field :title %>

  <p>Description</p>
  <%= f.text_field :description %>

  <p>Tags</p>
  <%= f.text_field :tag_list %>

  <p><%= f.submit %></p>
<% end %>

app/views/pieces/all_pieces.html.erb
<!-- Show all pieces -->
<script type="text/javascript">
  $(document).ready(function(){
      zoomHover();
  })
</script>

<h1 class="debugx ta-cen mb-2 mt-2">Pieces</h1>
<div class="line span-12-d mb-4"></div>

<div class="debugx col span-1-d ml-4 mt--2 d-inb">
  <h3>Category</h3>
  <p><%= link_to "All", pieces_path %></p>
    <% @tags.each do |tag| %>
       <p><%= link_to tag, tag_path(tag) %></p>
    <% end %>
</div>

<div class="debugx span-11-d ">
  <div class="debugx ml-25">

    <div id="target"></div>

      <div class="debugx ">
      <% @pieces.each do |piece| %>
      <% artist = Artist.find(piece.artist_id) %>

          <div class="debugx fl-end m-1 viewport">
            <a class="pic" href="<%= piece.image.url %>" data-lightbox="ex-1" data-title="<a class='lb-title' href='/artists/<%= artist.id %>'>by: <%= artist.name %></a>">
              <span class="dark-background">
                <%= piece.title %>
                <em>by <%= artist.name %></em>
              </span>
              <img src="<%= piece.image.url %>" alt="Piece Pic" />
            </a>
          </div>

      <% end %>
      </div>

  </div>
</div>

<!-- buffer for footer -->
<div class="col mb-8"></div>

app/views/pieces/create.html.erb
<h1>Pieces#create</h1>
<p>Find me in app/views/pieces/create.html.erb</p>

app/views/pieces/destroy.html.erb
<h1>Pieces#destroy</h1>
<p>Find me in app/views/pieces/destroy.html.erb</p>

app/views/pieces/edit.html.erb
<h1>Pieces#edit</h1>
<p>Find me in app/views/pieces/edit.html.erb</p>

<%= render partial: "partials/form_edit_piece_space", locals: { picture: @piece, user: @artist } %>

app/views/pieces/index.html.erb
<h1>Pieces#index</h1>

<h2><%= @artist.name  %> Pieces</h2>

<% @pieces.each do |piece| %>
  <div>
    <div><%= link_to image_tag(piece.img), artist_piece_path(piece.artist_id, piece) %></div>
    <p>Title: <%= piece.title %></p>
    <p>Description: <%= piece.description %></p>
    <p>Tags: <%= piece.tag_list.join(" ") %></p>

  <% if session[:artist_id] == @artist.id %>
    <button><%= link_to "Edit", edit_artist_piece_path(piece.artist_id, piece) %></button>
    <button><%= link_to "Remove", artist_piece_path(piece.artist_id, piece), method: :delete,data: { confirm: 'Are you sure?' } %></button>
  <% end %>
  </div>

<% end %>

app/views/pieces/new.html.erb
<h1>Pieces#new</h1>
<p>Find me in app/views/pieces/new.html.erb</p>

<p>form for creating a new piece</p>

<%= render partial: "partials/form_new_piece_space", locals: { user: @artist, picture: @artist.pieces.build } %>

app/views/pieces/show.html.erb
<h2><%= @piece.title %></h2>
<div class="debug">
  <a href="<%= @piece.img %>" data-lightbox="ex-1">
    <img src="<%= @piece.img %>" alt="Artist's Piece.img">
  </a>
</div>

<p class="debug"><%= @piece.description %></p>

  <div class="debug">
    <img src="http://www.wrapchic.in/images/offer.png" height=15, width=15>
    <% @piece.tag_list.each do |tag| %>
      <button class="ft-sm"><%= link_to tag, tag_path(tag), class: "gray" %></button>
    <% end %>
  </div>

<br>
<h3 class="debug"><strong>Artist: <%= link_to @artist.name, artist_path(@artist) %></strong></h3>


  <% if session[:artist_id] == @artist.id %>
    <button><%= link_to "Edit", edit_artist_piece_path(@piece.artist_id, @piece) %></button>
    <button><%= link_to "Remove", artist_piece_path(@piece.artist_id, @piece), method: :delete,data: { confirm: 'Are you sure?' } %></button>
  <% end %>

app/views/pieces/update.html.erb
<h1>Pieces#update</h1>
<p>Find me in app/views/pieces/update.html.erb</p>