config/routes.rb
Rails.application.routes.draw do
  root 'galleryhomepage#index'

  controller :about do
    get 'about-us' => 'about#index'
  end

  get 'tags/show'

  get 'api/pieces' => 'galleryhomepage#api'

  resources :organizations do
    resources :spaces
  end

  controller :artists do
    get 'local_artists' => 'artists#local_artists'
    get 'user_location' => 'artists#user_location'
  end

  controller :spaces do
    get 'spaces' => 'spaces#all_spaces'
    
  end

  controller :pieces do
    get 'pieces' => 'pieces#all_pieces'
  end

  resources :tags, only: [:show]

  resources :artists do
    resources :pieces
  end

  resources :sessions, only: [:new, :create, :destroy]

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    post 'logout' => :destroy
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :spaces
  has_secure_password
  geocoded_by :address
  after_validation :geocode
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
  end

  def show
    @organization = Organization.find_by(id: params[:id])
    @spaces = @organization.spaces
    @citystate = @organization.address.scan(/(.+?),\s*(.+?)(?:,\s|\s\s)(.+?)\s(\d{5})/)
    @location= @citystate[0][1] + ", " + @citystate[0][2]
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organization_path(@organization)
    else
      render 'new'
    end
  end

  def edit
    @organization = Organization.find_by(id: params[:id])
  end

  def update
    @organization = Organization.find_by(id: params[:id])
    if @organization.update(organization_params)
      redirect_to organization_path
    else
      render 'edit'
    end
  end

  def destroy
    @organization = Organization.find_by(id: params[:organization_id])
    @organization.destroy
    redirect_to root_path
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :email, :password, :address, :facebook, :twitter, :website, :bio, :avatar, :latitude, :longitude)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for @organization, class:"form-horizontal" do |f| %>
<form>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.text_field :avatar, class:"form-control", placeholder:"myimagehostingsite.com/coolavatar.jpg" %>
  </div>
  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control", placeholder:"Chris Doe" %>
  </div>
  <div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class:"form-control", placeholder:"chris@example.com" %>
  </div>
  <div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class:"form-control", placeholder:"MyTot3sSecurePassw0r!ds" %>
  </div>
  <div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address, class:"form-control", placeholder:"Street, City, State, Zipcode" %>
  </div>
  <div class="form-group">
  <%= f.label :facebook %>
  <%= f.text_field :facebook, class:"form-control", placeholder:"facebook.com/myfacebookpage" %>
  </div>
  <div class="form-group">
  <%= f.label :twitter %>
  <%= f.text_field :twitter, class:"form-control", placeholder:"@handle" %>
  </div>
  <div class="form-group">
  <%= f.label :website %>
  <%= f.text_field :website, class:"form-control", placeholder:"www.example.com" %>
  </div>
  <div class="form-group">
  <%= f.label :bio %>
  <%= f.text_field :bio, class:"form-control", placeholder:"Here's a blurb about me" %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>

  <% end %>
</form>
<br>
<%= link_to "Destroy Profile", @organization,class: 'btn btn-primary', method: :delete %>

app/views/organizations/create.html.erb
<h1>Organizations#create</h1>
<p>Find me in app/views/organizations/create.html.erb</p>

app/views/organizations/destroy.html.erb
<h1>Organizations#destroy</h1>
<p>Find me in app/views/organizations/destroy.html.erb</p>

app/views/organizations/edit.html.erb
<h1>Edit <%= @organization.name %>'s Profile</h1>

<%= render 'form' %>

app/views/organizations/index.html.erb
<h1>Organizations#index</h1>
<p>Find me in app/views/organizations/index.html.erb</p>

app/views/organizations/new.html.erb
<h1>Organization Sign-Up</h1>

<%= render 'form' %>

app/views/organizations/show.html.erb
<div class=" mt-2">
 <img class="m0-a profpic b-black-1" src="<%= @organization.avatar %>">
</div>
 <div class="bo-b-black-2 p-b-1 mb-4">
    <div class="span-3-d m0-a ta-c">
        <h1><%=@organization.name %></h1>
    </div>
    <div class="span-3-d m0-a ta-c">
        <a href="<%=@organization.website%>"><%= @organization.website %></a>
    </div>

    <div class="span-3-d m0-a ta-c p-t-2 p-b-2">
        <%=@organization.bio %>
    </div>
    <div class="span-3-d m0-a ta-c">
        <a href="<%=@organization.email%>"><%= @organization.email %></a>
    </div>
    <div class="span-3-d m0-a ta-c">
        <h4><%=@location%><h4>
        </div>
        <div class="social-media span-3-d m0-a ta-c">
            <% if @organization.twitter %>
            <a class="btn card-btn btn-primary btn-twitter btn-sm" href="<%= "http://twitter.com/#{@organization.twitter}" %>">
                <i>t</i>
            </a>
            <% end %>
            <% if @organization.facebook %>
            <a class="btn card-btn btn-primary btn-sm" rel="publisher"
            href="<%= "http://#{@organization.facebook}" %>">
            <i>f</i>
        </a>
        <% end %>
    </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
      zoomHover();
  })
</script>
<div class="debugx span-11-d mb-15 ">
  <div class="debugx ml-25">

    <div id="target"></div>
    <div class="debugx allpics">
        <% @organization.spaces.each do |space| %>
        <div class="debugx fl-end m-1 viewport">
            <a class="pic" href="<%= space.image.url %>" data-lightbox="ex-1" >
                <span class="dark-background"> <%= space.title %> <em>by <%= @organization.name %></em></span>
                <img src="<%= space.image.url(:thumb) %>" alt="Piece Pic" class="image-style" />
            </a>
        </div>
        <% end %>

    </div>
    <% if session[:organization_id] == @organization.id %>
    <%= link_to new_organization_space_path(@organization) do %>
    <div class="debugx fl-end m-1 viewport new b-black-dashed-2"></div>
    <% end %>
<% end %>
<div class="col mb-8"></div>
</div>

</div>

app/views/organizations/update.html.erb
<h1>Organizations#update</h1>
<p>Find me in app/views/organizations/update.html.erb</p>